In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [6]:
x = np.array([[1., 2.], [np.nan, 3.], [np.nan, np.nan]])
x[~np.isnan(x)]

array([1., 2., 3.])

`~` равносильно `!` вроде

In [38]:
x = np.array([[0, 1], [1, 1], [2, 2]])
rowsum = x.sum(-1)
x[rowsum <= 2, :]
rowsum.shape
rowsum

array([1, 2, 4])

In [40]:
rowsum = x.sum(-1, keepdims=True)
rowsum.shape
rowsum

array([[1],
       [2],
       [4]])

In [68]:
np.seed = 7
train_data = np.random.normal(size=(100, 2))
train_labels = np.zeros(100)

train_data = np.r_[train_data, np.random.normal(size=(100, 2), loc=2)]
np.r_?
